### ISSUE TITLE
Portfolio solver cancellation

### ISSUE THREAD

**Issue by niyaznigmatullin** [UnitTestBot/ksmt#127]
I have a suggestion (probably I can make a PR, but I'm not very familiar with the code).

`KSolverRunner` unlike `KPortfolioSolver` allowed us to cancel suspending methods from the outside, for `KPortfolioSolver` it doesn't work as far as I tried to investigate the reason is `awaitFirstSolver` function.

This line throws an exception on cancellation https://github.com/UnitTestBot/ksmt/blob/6803209da1c54a995de9ba4f92f8633bbb421cb8/ksmt-runner/src/main/kotlin/io/ksmt/solver/portfolio/KPortfolioSolver.kt#L319, and the exception is not handled. 

I suggest to catch the exception inside `awaitFirstSolver` and kill all active inner solvers.

(If you think this is doable and can be done straightforwardly, I will create a PR)

**Comment by Saloed** [comment]
In your solution you just cancel the coroutine and skip `deleteSolver` leaving the solver process pool in the incorrect state. 
The issue with `close` can be fixed with #129 

Does this fix works in your cases or maybe you have more complex scenarios?

**Comment by niyaznigmatullin** [comment]
Yes, I've checked, it works in my case. Thanks
