### ISSUE TITLE
DefaultValueSampler fails when creating values for custom size bitvectors

### ISSUE THREAD

**Issue by AbdullinAM** [UnitTestBot/ksmt#58]
`DefaultValueSimpler` uses [following code](https://github.com/UnitTestBot/ksmt/blob/654ece77b2bee079c625571ee14cc756d3be214e/ksmt-core/src/main/kotlin/org/ksmt/solver/model/DefaultValueSampler.kt#L35) to create a default value for bitvectors:
```kotlins
override fun <S : KBvSort> visit(sort: S): KExpr<T> = with(ctx) {
    mkBv("0", sort.sizeBits).asExpr(this@DefaultValueSampler.sort)
}
```

I.e. it creates a single-character length string. If the size of bitvector is not standard (i.e. not 1, 8, 16, 32, 64), `KContext` creates a `KBitVecCustomValue`.

However, constructor of `KBitVecCustomValue` contains [a check](https://github.com/UnitTestBot/ksmt/blob/654ece77b2bee079c625571ee14cc756d3be214e/ksmt-core/src/main/kotlin/org/ksmt/expr/KBitVecExprs.kt#L104) that ensures that the length of a string is equal to the bitsize of a bitvector sort:
```kotlin
require(binaryStringValue.length.toUInt() == sizeBits) {
    "Provided string $binaryStringValue consist of ${binaryStringValue.length} " +
            "symbols, but $sizeBits were expected"
}
```

So this results in `IllegalArgumentException` being thrown in the `KBitVecCustomValue` constructor.

Example for reproducing the error:
```kotlin
val solverManager: KSolverRunnerManager by lazy {
    KSolverRunnerManager(
        workerPoolSize = 1,
        hardTimeout = 10.seconds * 2,
        workerProcessIdleTimeout = 10.seconds,
    )
}
val ctx = KContext()
with(ctx) {
    val bv32Sort = ctx.mkBv32Sort()
    val customSort = ctx.mkBvSort(2U)
    val arraySort = ctx.mkArraySort(bv32Sort, customSort)

    val decl = ctx.mkConstDecl("a", arraySort)
    val index by bv32Sort
    val a by customSort

    val constraint = a eq decl.apply().store(ctx.mkBv(12), ctx.mkBv("11", 2U)).select(index)

    val solver = solverManager.createSolver(ctx, KZ3Solver::class)
    solver.assert(constraint)
    solver.assert(index eq ctx.mkBv(12))
    solver.check(1.seconds)
    val model = solver.model()
    println(model.eval(a, true))
    println(model.eval(decl.apply(), true))
}
```

**Comment by Saloed** [comment]
Already fixed in #57. If you don't want to wait until the next release, you can use ksmt version `bf8bc86055`.
