### ISSUE TITLE
Various performance issues

### ISSUE THREAD

**Issue by Saloed** [UnitTestBot/ksmt#8]
### Overview
This issue contains a list of known performance problems

### Z3
- [x] Don't create intermediate Expr objects. Use Z3 native pointers directly

### Bitwuzla
- [x] Faster JNI bidings

### Misc 
- [x] KSmt benchmarks

**Comment by korifey** [comment]
For native calls please consider using this library: https://github.com/apangin/nalim

**Comment by Saloed** [comment]
As for me, we can't use `nalim` as it requires additional jvm flags, which makes KSMT not easy-to-use

**Comment by korifey** [comment]
> As for me, we can't use `nalim` as it requires additional jvm flags, which makes KSMT not easy-to-use

Why? We start external JVM process and can set any flags we want.
